version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: biblioteca
    container_name: biblioteca-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - biblioteca

  db:
    image: mysql:5.7
    container_name: biblioteca-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
    #   MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #   MYSQL_PASSWORD: ${DB_PASSWORD}
    #  TESTANDO USO DE SECRETS
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 9031:3306
    volumes:
      - biblioteca_volumes:/var/lib/mysql
    networks:
      - biblioteca
    secrets:
    - db_password

  nginx:
    image: nginx:1.17-alpine
    container_name: biblioteca-nginx
    restart: unless-stopped
    ports:
      - 9030:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - biblioteca
      - ses_am

networks:
  biblioteca:
    driver: bridge
  ses_am:
    external:
      name: proxy_ses_fixed_network

volumes:
  biblioteca_volumes: {}
